# List of approved authors ID
BENNY_HINN = "BEHI"
BILLY_GRAHAM = "BIGR"
DEREK_PRINCE = "DEPR"
DR_FRANCIS_MYLES = "FRMY"
JAMES_W_GALL = "JWGA"
JOHN_KURIAN = "JOKU"
JOHN_BUNYAN = "JOBU"
REINHARD_BONNKE = "REBO"
SAM_WELLMAN = "SAWE"
WATCHMAN_NEE = "WANE"
WITNESS_LEE = "WILE"
WILLIAM_CAREY = "WICA"
ZAC_POONEN = "ZAPO"


# List of publishers ID
BIBLE_SOCIETY_OF_INDIA = "BSIN"
OUR_DAILY_BREAD_MINISTRERIES = "ODBM"


