LIBRARY_ROLES = {
    1: 'ADMIN',
    2: 'MODERATOR',
    3: 'MEMBER'
}


STATUS_CODE_CATEGORY = [
    "TRANSACTION",
    "BOOK",
    "ACCOUNT"
]

# Log files
APP_LOG_FILE = 'crjyouth_app.log'
AUTH_LOG_FILE = 'crjyouth_auth.log'

# Authentication Configuration
TOKEN_EXPIRY_HOURS = 12
PASSWORD_RESET_EXPIRY_MINUTES = 30
NONCE_EXPIRY_MINUTES = 10

# Rate Limiting Configuration
DEFAULT_RATE_LIMIT_REQUESTS = 5
DEFAULT_RATE_LIMIT_WINDOW_MINUTES = 15
LOGIN_RATE_LIMIT_REQUESTS = 5
LOGIN_RATE_LIMIT_WINDOW_MINUTES = 15
REGISTER_RATE_LIMIT_REQUESTS = 3
REGISTER_RATE_LIMIT_WINDOW_MINUTES = 15
PASSWORD_RESET_RATE_LIMIT_REQUESTS = 3
PASSWORD_RESET_RATE_LIMIT_WINDOW_MINUTES = 30
