MAX_BORROW_LIMIT = 3
LATE_FINE_AMOUNT = 100  # ₹
LOST_DAMAGE_FINE = 1000  # ₹
VALID_TRANSACTION_STATUSES = {'PENDING', 'OPEN', 'OVERDUE', 'CLOSED'}

STATUS_CODE_CATEGORY = [
    "TRANSACTION",
    "BOOK",
    "ACCOUNT"
]

# Log files
APP_LOG_FILE = 'crjyouth_app.log'
AUTH_LOG_FILE = 'crjyouth_auth.log'

# Authentication Configuration
TOKEN_EXPIRY_HOURS = 12
PASSWORD_RESET_EXPIRY_MINUTES = 30
NONCE_EXPIRY_MINUTES = 10

# Rate Limiting Configuration
DEFAULT_RATE_LIMIT_REQUESTS = 5
DEFAULT_RATE_LIMIT_WINDOW_MINUTES = 15
LOGIN_RATE_LIMIT_REQUESTS = 5
LOGIN_RATE_LIMIT_WINDOW_MINUTES = 15
REGISTER_RATE_LIMIT_REQUESTS = 3
REGISTER_RATE_LIMIT_WINDOW_MINUTES = 15
PASSWORD_RESET_RATE_LIMIT_REQUESTS = 3
PASSWORD_RESET_RATE_LIMIT_WINDOW_MINUTES = 30
