LIBRARY_ROLES = {
    1: 'ADMIN',
    2: 'MODERATOR',
    3: 'MEMBER'
}

TOKEN_PRICES = {
    'S1': 10.0,
    'S2': 25.0,
    'M1': 50.0,
    'M2':  75.0,
    'L1': 100.0,
    'L2': 150.0
}

DEFAULT_EXTENSION_FEE = 10.0
DEFAULT_DAMAGE_FEE = 100.0
EXTENSION_DAYS = 7

STATUS_CODE_CATEGORY = [
    "TRANSACTION",
    "BOOK",
    "ACCOUNT"
]

# Log files
INFRA_LOG_FILE = 'crjyouth_infra.log'
OPS_LOG_FILE = 'crjyouth_ops.log'
APP_LOG_FILE = 'crjyouth_app.log'
AUTH_LOG_FILE = 'crjyouth_auth.log'

# Authentication Configuration
TOKEN_EXPIRY_HOURS = 12
PASSWORD_RESET_EXPIRY_MINUTES = 30
NONCE_EXPIRY_MINUTES = 10

# Rate Limiting Configuration
DEFAULT_RATE_LIMIT_REQUESTS = 5
DEFAULT_RATE_LIMIT_WINDOW_MINUTES = 15
LOGIN_RATE_LIMIT_REQUESTS = 5
LOGIN_RATE_LIMIT_WINDOW_MINUTES = 15
REGISTER_RATE_LIMIT_REQUESTS = 3
REGISTER_RATE_LIMIT_WINDOW_MINUTES = 15
PASSWORD_RESET_RATE_LIMIT_REQUESTS = 3
PASSWORD_RESET_RATE_LIMIT_WINDOW_MINUTES = 30
